title: Runway
description: Runway
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

url: https://a-s-g93.github.io/neo4j-runway

aux_links:
  Template Repository: https://github.com/a-s-g93/neo4j-runway

defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"

