title: Runway
description: Runway
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-include-cache

url: https://a-s-g93.github.io/neo4j-runway

aux_links:
  Template Repository: https://github.com/a-s-g93/neo4j-runway


